[package]
name = "fit_file_native"
version = "0.1.1"
authors = []
edition = "2021"

[lib]
name = "fit_file_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.1"
fitparser = "0.10.0"
